// === Kiyo日语 - 标准全量词汇库 (dict_vocab.js) ===
const bulkVocab = [

    // --- N5 标准词汇 (已格式化) ---
  { "level": "N5", "main": "会う", "kana": "あう", "meaning": "见面", "example": "明日、友達に会います。(明天和朋友见面。)" },
  { "level": "N5", "main": "青", "kana": "あお", "meaning": "蓝色 / 青色", "example": "信号が青になりました。(信号灯变绿了。)" },
  { "level": "N5", "main": "青い", "kana": "あおい", "meaning": "蓝色的", "example": "今日は青い空がきれいです。(今天蓝色的天空很漂亮。)" },
  { "level": "N5", "main": "赤", "kana": "あか", "meaning": "红色", "example": "赤が好きです。(我喜欢红色。)" },
  { "level": "N5", "main": "赤い", "kana": "あかい", "meaning": "红色的", "example": "あの赤い車を見てください。(请看那辆红色的车。)" },
  { "level": "N5", "main": "明るい", "kana": "あかるい", "meaning": "明亮的 / 开朗的", "example": "この部屋はとても明るいです。(这个房间很明亮。)" },
  { "level": "N5", "main": "秋", "kana": "あき", "meaning": "秋天", "example": "秋は涼しくて好きです。(秋天很凉爽，我很喜欢。)" },
  { "level": "N5", "main": "開ける", "kana": "あける", "meaning": "打开", "example": "ドアを開けてください。(请把门打开。)" },
  { "level": "N5", "main": "上げる", "kana": "あげる", "meaning": "举起 / 给", "example": "手を上げてください。(请举手。)" },
  { "level": "N5", "main": "朝", "kana": "あさ", "meaning": "早上", "example": "毎朝6時に起きます。(每天早上6点起床。)" },
  { "level": "N5", "main": "朝御飯", "kana": "あさごはん", "meaning": "早饭", "example": "もう朝御飯を食べましたか。(已经吃过早饭了吗？)" },
  { "level": "N5", "main": "あさって", "kana": "あさって", "meaning": "后天", "example": "あさって、日本へ行きます。(后天去日本。)" },
  { "level": "N5", "main": "足", "kana": "あし", "meaning": "脚 / 腿", "example": "彼は足が長いです。(他的腿很长。)" },
  { "level": "N5", "main": "あそこ", "kana": "あそこ", "meaning": "那里", "example": "トイレはあそこです。(厕所在那里。)" },
  { "level": "N5", "main": "遊ぶ", "kana": "あそぶ", "meaning": "玩 / 玩耍", "example": "日曜日は公園で遊びます。(星期天在公园玩。)" },
  { "level": "N5", "main": "頭", "kana": "あたま", "meaning": "头 / 头脑", "example": "頭が痛いです。(头很痛。)" },
  { "level": "N5", "main": "新しい", "kana": "あたらしい", "meaning": "新的", "example": "新しい靴を買いました。(买了新鞋子。)" },
  { "level": "N5", "main": "あちら", "kana": "あちら", "meaning": "那边 (礼貌)", "example": "あちらへどうぞ。(请往那边走。)" },
  { "level": "N5", "main": "暑い", "kana": "あつい", "meaning": "热 (天气)", "example": "今日はとても暑いですね。(今天真热啊。)" },
  { "level": "N5", "main": "熱い", "kana": "あつい", "meaning": "烫 / 热 (物体)", "example": "このお茶は熱いです。(这茶很烫。)" },
  { "level": "N5", "main": "厚い", "kana": "あつい", "meaning": "厚", "example": "あの本は厚いです。(那本书很厚。)" },
  { "level": "N5", "main": "あっち", "kana": "あっち", "meaning": "那边 (口语)", "example": "あっちに行きましょう。(去那边吧。)" },
  { "level": "N5", "main": "あなた", "kana": "あなた", "meaning": "你", "example": "これはあなたの傘ですか。(这是你的伞吗？)" },
  { "level": "N5", "main": "兄", "kana": "あに", "meaning": "哥哥 (自称)", "example": "兄は東京に住んでいます。(我哥哥住在东京。)" },
  { "level": "N5", "main": "姉", "kana": "あね", "meaning": "姐姐 (自称)", "example": "姉は銀行員です。(我姐姐是银行职员。)" },
  { "level": "N5", "main": "あの", "kana": "あの", "meaning": "那个", "example": "あの人は誰ですか。(那个人是谁？)" },
  { "level": "N5", "main": "アパート", "kana": "アパート", "meaning": "公寓", "example": "きれいなアパートですね。(真是漂亮的公寓啊。)" },
  { "level": "N5", "main": "あびる", "kana": "あびる", "meaning": "淋 / 浴", "example": "毎日シャワーを浴びます。(每天淋浴。)" },
  { "level": "N5", "main": "危ない", "kana": "あぶない", "meaning": "危险", "example": "危ないですから、止まってください。(因为危险，请停下来。)" },
  { "level": "N5", "main": "あまり", "kana": "あまり", "meaning": "不太... (接否定) / 剩余", "example": "私はあまりお酒を飲みません。(我不太喝酒。)" },
  { "level": "N5", "main": "雨", "kana": "あめ", "meaning": "雨", "example": "外は雨が降っています。(外面正在下雨。)" },
  { "level": "N5", "main": "飴", "kana": "あめ", "meaning": "糖果", "example": "飴を食べますか。(要吃糖吗？)" },
  { "level": "N5", "main": "洗う", "kana": "あらう", "meaning": "洗", "example": "ご飯の前に手を洗います。(吃饭前洗手。)" },
  { "level": "N5", "main": "ある", "kana": "ある", "meaning": "有 (非生命)", "example": "机の上に本があります。(桌子上有书。)" },
  { "level": "N5", "main": "歩く", "kana": "あるく", "meaning": "走路", "example": "駅まで歩きます。(走到车站。)" },
  { "level": "N5", "main": "あれ", "kana": "あれ", "meaning": "那个 (远称)", "example": "あれは何ですか。(那个是什么？)" },
  { "level": "N5", "main": "いいえ", "kana": "いいえ", "meaning": "不 / 不是", "example": "いいえ、違います。(不，不对。)" },
  { "level": "N5", "main": "家", "kana": "いえ", "meaning": "家 / 房子", "example": "ここが私の家です。(这是我的家。)" },
  { "level": "N5", "main": "いかが", "kana": "いかが", "meaning": "如何 (礼貌)", "example": "お茶はいかがですか。(来点茶怎么样？)" },
  { "level": "N5", "main": "行く", "kana": "いく", "meaning": "去", "example": "学校へ行きます。(去学校。)" },
  { "level": "N5", "main": "いくつ", "kana": "いくつ", "meaning": "几个 / 几岁", "example": "りんごはいくつありますか。(苹果有几个？)" },
  { "level": "N5", "main": "いくら", "kana": "いくら", "meaning": "多少钱", "example": "これはいくらですか。(这个多少钱？)" },
  { "level": "N5", "main": "池", "kana": "いけ", "meaning": "池塘", "example": "この池には魚がいません。(这个池塘里没有鱼。)" },
  { "level": "N5", "main": "医者", "kana": "いしゃ", "meaning": "医生", "example": "私は医者になりたいです。(我想成为医生。)" },
  { "level": "N5", "main": "いす", "kana": "いす", "meaning": "椅子", "example": "いすに座ってください。(请坐在椅子上。)" },
  { "level": "N5", "main": "忙しい", "kana": "いそがしい", "meaning": "忙碌", "example": "今週はとても忙しいです。(这周非常忙。)" },
  { "level": "N5", "main": "痛い", "kana": "いたい", "meaning": "痛", "example": "お腹が痛いです。(肚子痛。)" },
  { "level": "N5", "main": "一", "kana": "いち", "meaning": "一", "example": "一から始めましょう。(从一开始吧。)" },
  { "level": "N5", "main": "いちばん", "kana": "いちばん", "meaning": "最 / 第一", "example": "これが一番好きです。(最喜欢这个。)" },
  { "level": "N5", "main": "いつ", "kana": "いつ", "meaning": "什么时候", "example": "誕生日はいつですか。(生日是什么时候？)" },
  { "level": "N5", "main": "五日", "kana": "いつか", "meaning": "五号 / 五天", "example": "来月の五日に会います。(下个月五号见面。)" },
  { "level": "N5", "main": "一緒", "kana": "いっしょ", "meaning": "一起", "example": "一緒に帰りましょう。(一起回去吧。)" },
  { "level": "N5", "main": "五つ", "kana": "いつつ", "meaning": "五个", "example": "りんごを五つください。(请给我五个苹果。)" },
  { "level": "N5", "main": "犬", "kana": "いぬ", "meaning": "狗", "example": "白い犬がいます。(有一只白色的狗。)" },
  { "level": "N5", "main": "今", "kana": "いま", "meaning": "现在", "example": "今、何時ですか。(现在几点？)" },
  { "level": "N5", "main": "意味", "kana": "いみ", "meaning": "意思", "example": "その言葉の意味が分かりません。(我不懂那个词的意思。)" },
  { "level": "N5", "main": "妹", "kana": "いもうと", "meaning": "妹妹", "example": "妹は学生です。(妹妹是学生。)" },
  { "level": "N5", "main": "嫌", "kana": "いや", "meaning": "讨厌 / 不愿意", "example": "そんなことは嫌です。(那样的事我不愿意。)" },
  { "level": "N5", "main": "要る", "kana": "いる", "meaning": "需要", "example": "お金が要ります。(需要钱。)" },
  { "level": "N5", "main": "入れる", "kana": "いれる", "meaning": "放入", "example": "かばんに本を入れます。(把书放进包里。)" },
  { "level": "N5", "main": "色", "kana": "いろ", "meaning": "颜色", "example": "どんな色が好きですか。(喜欢什么颜色？)" },
  { "level": "N5", "main": "いろいろ", "kana": "いろいろ", "meaning": "各种各样", "example": "店にはいろいろな物があります。(店里有各种各样的东西。)" },
  { "level": "N5", "main": "後ろ", "kana": "うしろ", "meaning": "后面", "example": "ドアの後ろに誰かいます。(门后面有人。)" },
  { "level": "N5", "main": "薄い", "kana": "うすい", "meaning": "薄 / (味道、颜色)淡", "example": "この本は薄いです。(这本书很薄。)" },
  { "level": "N5", "main": "歌", "kana": "うた", "meaning": "歌曲", "example": "日本の歌を歌います。(唱日本歌。)" },
  { "level": "N5", "main": "歌う", "kana": "うたう", "meaning": "唱歌", "example": "カラオケで歌いました。(在卡拉OK唱了歌。)" },
  { "level": "N5", "main": "生まれる", "kana": "うまれる", "meaning": "出生", "example": "日本で生まれました。(在日本出生。)" },
  { "level": "N5", "main": "海", "kana": "うみ", "meaning": "海", "example": "夏は海へ行きます。(夏天去海边。)" },
  { "level": "N5", "main": "売る", "kana": "うる", "meaning": "卖", "example": "古い車を売りました。(卖掉了旧车。)" },
  { "level": "N5", "main": "煩い", "kana": "うるさい", "meaning": "吵闹 / 烦人", "example": "隣の部屋が煩いです。(隔壁房间很吵。)" },
  { "level": "N5", "main": "上着", "kana": "うわぎ", "meaning": "上衣 / 外套", "example": "寒いので上着を着ます。(因为冷，穿上外套。)" },
  { "level": "N5", "main": "絵", "kana": "え", "meaning": "画 / 图画", "example": "きれいな絵ですね。(很漂亮的画啊。)" },
  { "level": "N5", "main": "映画", "kana": "えいが", "meaning": "电影", "example": "明日、映画を見ます。(明天看电影。)" },
  { "level": "N5", "main": "映画館", "kana": "えいがかん", "meaning": "电影院", "example": "映画館へ行きましょう。(去电影院吧。)" },
  { "level": "N5", "main": "英語", "kana": "えいご", "meaning": "英语", "example": "英語を勉強しています。(正在学习英语。)" },
  { "level": "N5", "main": "ええ", "kana": "ええ", "meaning": "嗯 / 是的 (口语)", "example": "ええ、そうです。(嗯，是的。)" },
  { "level": "N5", "main": "駅", "kana": "えき", "meaning": "车站", "example": "駅まで歩きます。(走到车站。)" },
  { "level": "N5", "main": "エレベーター", "kana": "エレベーター", "meaning": "电梯", "example": "エレベーターに乗りましょう。(坐电梯吧。)" },
  { "level": "N5", "main": "鉛筆", "kana": "えんぴつ", "meaning": "铅笔", "example": "鉛筆を貸してください。(请借我铅笔。)" },
  { "level": "N5", "main": "おいしい", "kana": "おいしい", "meaning": "好吃", "example": "このパンはおいしいです。(这个面包很好吃。)" },
  { "level": "N5", "main": "多い", "kana": "おおい", "meaning": "多", "example": "今日は人が多いです。(今天人很多。)" },
  { "level": "N5", "main": "大きい", "kana": "おおきい", "meaning": "大", "example": "大きい家ですね。(好大的房子啊。)" },
  { "level": "N5", "main": "大きな", "kana": "おおきな", "meaning": "大的 (连体词)", "example": "大きな木があります。(有一棵大树。)" },
  { "level": "N5", "main": "大勢", "kana": "おおぜい", "meaning": "很多人", "example": "大勢の人が集まりました。(聚集了很多人。)" },
  { "level": "N5", "main": "お母さん", "kana": "おかあさん", "meaning": "母亲 / 妈妈 (敬称)", "example": "お母さんは元気ですか。(你母亲身体好吗？)" },
  { "level": "N5", "main": "お菓子", "kana": "おかし", "meaning": "点心 / 零食", "example": "お菓子を食べませんか。(要吃点心吗？)" },
  { "level": "N5", "main": "お金", "kana": "おかね", "meaning": "钱", "example": "お金がありません。(没有钱。)" },
  { "level": "N5", "main": "起きる", "kana": "おきる", "meaning": "起床", "example": "毎朝６時に起きます。(每天早上6点起床。)" },
  { "level": "N5", "main": "置く", "kana": "おく", "meaning": "放置", "example": "荷物をここに置いてください。(请把行李放在这里。)" },
  { "level": "N5", "main": "奥さん", "kana": "おくさん", "meaning": "妻子 / 太太 (敬称)", "example": "田中さんの奥さんは優しいです。(田中先生的太太很温柔。)" },
  { "level": "N5", "main": "お酒", "kana": "おさけ", "meaning": "酒", "example": "父はお酒が好きです。(父亲喜欢喝酒。)" },
  { "level": "N5", "main": "お皿", "kana": "おさら", "meaning": "盘子", "example": "お皿を洗いました。(洗了盘子。)" },
  { "level": "N5", "main": "伯父", "kana": "おじ", "meaning": "伯父", "example": "伯父は医者です。(伯父是医生。)" },
  { "level": "N5", "main": "叔父", "kana": "おじ", "meaning": "叔叔", "example": "叔父と遊びました。(和叔叔一起玩。)" },
  { "level": "N5", "main": "教える", "kana": "おしえる", "meaning": "教 / 告诉", "example": "住所を教えてください。(请告诉我地址。)" },
  { "level": "N5", "main": "押す", "kana": "おす", "meaning": "推 / 按", "example": "ボタンを押してください。(请按按钮。)" },
  { "level": "N5", "main": "遅い", "kana": "おそい", "meaning": "慢 / 晚", "example": "帰るのが遅くなりました。(回去晚了。)" },
  { "level": "N5", "main": "お茶", "kana": "おちゃ", "meaning": "茶", "example": "お茶を飲みますか。(要喝茶吗？)" },
  { "level": "N5", "main": "お手洗い", "kana": "おてあらい", "meaning": "洗手间 / 厕所", "example": "お手洗いはどこですか。(洗手间在哪里？)" },
  { "level": "N5", "main": "お父さん", "kana": "おとうさん", "meaning": "父亲 / 爸爸 (敬称)", "example": "お父さんはお元気ですか。(你父亲身体好吗？)" },
  { "level": "N5", "main": "男", "kana": "おとこ", "meaning": "男人 / 男性", "example": "あの男の人は誰ですか。(那个男人是谁？)" },
  { "level": "N5", "main": "男の子", "kana": "おとこのこ", "meaning": "男孩", "example": "男の子が公園で遊んでいます。(男孩在公园里玩。)" },
  { "level": "N5", "main": "大人", "kana": "おとな", "meaning": "成年人 / 大人", "example": "彼はもう大人です。(他已经是大人了。)" },
  { "level": "N5", "main": "おなか", "kana": "おなか", "meaning": "肚子", "example": "おなかがすきました。(肚子饿了。)" },
  { "level": "N5", "main": "同じ", "kana": "おなじ", "meaning": "相同 / 一样", "example": "私と彼は同じ年です。(我和他同岁。)" },
  { "level": "N5", "main": "お兄さん", "kana": "おにいさん", "meaning": "哥哥 (敬称) / 年轻小伙子", "example": "田中さんのお兄さんは背が高いです。(田中先生的哥哥个子很高。)" },
  { "level": "N5", "main": "お姉さん", "kana": "おねえさん", "meaning": "姐姐 (敬称) / 年轻姑娘", "example": "きれいなお姉さんがいます。(有一位漂亮的姐姐。)" },
  { "level": "N5", "main": "おばあさん", "kana": "おばあさん", "meaning": "祖母 / 老奶奶 (敬称)", "example": "電車でおばあさんに席を譲りました。(在电车上给老奶奶让座了。)" },
  { "level": "N5", "main": "お風呂", "kana": "おふろ", "meaning": "澡堂 / 洗澡水", "example": "ゆっくりお風呂に入りたいです。(想舒舒服服地泡个澡。)" },
  { "level": "N5", "main": "お弁当", "kana": "おべんとう", "meaning": "便当 / 盒饭", "example": "毎日、母がお弁当を作ります。(妈妈每天做便当。)" },
  { "level": "N5", "main": "覚える", "kana": "おぼえる", "meaning": "记住 / 记得 / 学会", "example": "新しい漢字を覚えました。(记住了新的汉字。)" },
  { "level": "N5", "main": "おまわりさん", "kana": "おまわりさん", "meaning": "巡警 / 警察先生", "example": "おまわりさんに道を聞きました。(向巡警问了路。)" },
  { "level": "N5", "main": "重い", "kana": "おもい", "meaning": "重", "example": "この荷物はとても重いです。(这个行李很重。)" },
  { "level": "N5", "main": "おもしろい", "kana": "おもしろい", "meaning": "有趣 / 好玩", "example": "このゲームはおもしろいです。(这个游戏很有趣。)" },
  { "level": "N5", "main": "泳ぐ", "kana": "およぐ", "meaning": "游泳", "example": "夏はプールで泳ぎます。(夏天在游泳池游泳。)" },
  { "level": "N5", "main": "降りる", "kana": "おりる", "meaning": "下 (车、山等)", "example": "次の駅で降ります。(在下一站下车。)" },
  { "level": "N5", "main": "終る", "kana": "おわる", "meaning": "结束", "example": "仕事は5時に終わります。(工作5点结束。)" },
  { "level": "N5", "main": "音楽", "kana": "おんがく", "meaning": "音乐", "example": "音楽を聞くのが好きです。(喜欢听音乐。)" },
  { "level": "N5", "main": "女", "kana": "おんな", "meaning": "女人 / 女性", "example": "部屋に女の人がいます。(房间里有位女性。)" },
  { "level": "N5", "main": "女の子", "kana": "おんなのこ", "meaning": "女孩", "example": "かわいい女の子ですね。(可爱的女孩子啊。)" },
  { "level": "N5", "main": "外国", "kana": "がいこく", "meaning": "外国", "example": "外国へ旅行に行きます。(去国外旅行。)" },
  { "level": "N5", "main": "外国人", "kana": "がいこくじん", "meaning": "外国人", "example": "教室に外国人がいます。(教室里有外国人。)" },
  { "level": "N5", "main": "会社", "kana": "かいしゃ", "meaning": "公司", "example": "父は会社で働いています。(父亲在公司工作。)" },
  { "level": "N5", "main": "階段", "kana": "かいだん", "meaning": "楼梯", "example": "階段を上りましょう。(上楼梯吧。)" },
  { "level": "N5", "main": "買い物", "kana": "かいもの", "meaning": "购物 / 买东西", "example": "デパートへ買い物に行きます。(去百货商店购物。)" },
  { "level": "N5", "main": "買う", "kana": "かう", "meaning": "买", "example": "本屋で辞書を買いました。(在书店买了字典。)" },
  { "level": "N5", "main": "返す", "kana": "かえす", "meaning": "归还 / 还", "example": "図書館に本を返します。(把书还给图书馆。)" },
  { "level": "N5", "main": "帰る", "kana": "かえる", "meaning": "回家 / 回去", "example": "もうすぐ家に帰ります。(马上就回家。)" },
  { "level": "N5", "main": "かかる", "kana": "かかる", "meaning": "花费 (时间、金钱)", "example": "駅まで10分かかります。(到车站要花10分钟。)" },
  { "level": "N5", "main": "かぎ", "kana": "かぎ", "meaning": "钥匙 / 锁", "example": "部屋のかぎを忘れました。(忘记了房间钥匙。)" },
  { "level": "N5", "main": "書く", "kana": "かく", "meaning": "写", "example": "ここに名前を書いてください。(请在这里写上名字。)" },
  { "level": "N5", "main": "学生", "kana": "がくせい", "meaning": "学生", "example": "私は大学の学生です。(我是大学生。)" },
  { "level": "N5", "main": "かける", "kana": "かける", "meaning": "打 (电话) / 戴 (眼镜)", "example": "友達に電話をかけました。(给朋友打了电话。)" },
  { "level": "N5", "main": "傘", "kana": "かさ", "meaning": "伞", "example": "雨ですから、傘を持って行きます。(因为下雨，带伞去。)" },
  { "level": "N5", "main": "貸す", "kana": "かす", "meaning": "借给", "example": "消しゴムを貸してください。(请借给我橡皮。)" },
  { "level": "N5", "main": "風", "kana": "かぜ", "meaning": "风", "example": "強い風が吹いています。(正刮着大风。)" },
  { "level": "N5", "main": "風邪", "kana": "かぜ", "meaning": "感冒", "example": "風邪を引いて、頭が痛いです。(感冒了，头很痛。)" },
  { "level": "N5", "main": "家族", "kana": "かぞく", "meaning": "家人 / 家族", "example": "家族は5人です。(家里有5口人。)" },
  { "level": "N5", "main": "学校", "kana": "がっこう", "meaning": "学校", "example": "学校は8時に始まります。(学校8点开始上课。)" },
  { "level": "N5", "main": "カップ", "kana": "カップ", "meaning": "杯子", "example": "コーヒーをカップに入れます。(把咖啡倒进杯子里。)" },
  { "level": "N5", "main": "家庭", "kana": "かてい", "meaning": "家庭", "example": "明るい家庭を作りたいです。(想建立一个开朗的家庭。)" },
  { "level": "N5", "main": "かばん", "kana": "かばん", "meaning": "包 / 书包", "example": "そのかばんは誰のですか。(那个包是谁的？)" },
  { "level": "N5", "main": "花瓶", "kana": "かびん", "meaning": "花瓶", "example": "花瓶に花を入れます。(把花放进花瓶。)" },
  { "level": "N5", "main": "紙", "kana": "かみ", "meaning": "纸", "example": "紙とペンをください。(请给我纸和笔。)" },
  { "level": "N5", "main": "カメラ", "kana": "カメラ", "meaning": "相机 / 照相机", "example": "新しいカメラを買いました。(买了新相机。)" },
  { "level": "N5", "main": "火曜日", "kana": "かようび", "meaning": "星期二", "example": "来週の火曜日は休みです。(下周二休息。)" },
  { "level": "N5", "main": "借りる", "kana": "かりる", "meaning": "借入", "example": "図書館で本を借ります。(在图书馆借书。)" },
  { "level": "N5", "main": "軽い", "kana": "かるい", "meaning": "轻", "example": "この靴は軽くて歩きやすいです。(这双鞋很轻，好走路。)" },
  { "level": "N5", "main": "カレー", "kana": "カレー", "meaning": "咖喱", "example": "今日の晩ご飯はカレーです。(今天的晚饭是咖喱。)" },
  { "level": "N5", "main": "カレンダー", "kana": "カレンダー", "meaning": "日历", "example": "カレンダーに予定を書きます。(在日历上写计划。)" },
  { "level": "N5", "main": "かわいい", "kana": "かわいい", "meaning": "可爱", "example": "この犬はとてもかわいいです。(这只狗非常可爱。)" },
  { "level": "N5", "main": "漢字", "kana": "かんじ", "meaning": "汉字", "example": "漢字を書くのは難しいです。(写汉字很难。)" },
  { "level": "N5", "main": "木", "kana": "き", "meaning": "树 / 木头", "example": "庭に大きな木があります。(院子里有一棵大树。)" },
  { "level": "N5", "main": "黄色い", "kana": "きいろい", "meaning": "黄色的", "example": "黄色いかばんを買いました。(买了个黄色的包。)" },
  { "level": "N5", "main": "消える", "kana": "きえる", "meaning": "消失 / 熄灭", "example": "部屋の電気が消えました。(房间的灯灭了。)" },
  { "level": "N5", "main": "聞く", "kana": "きく", "meaning": "听 / 问", "example": "先生に道を聞きます。(向老师问路。)" },
  { "level": "N5", "main": "北", "kana": "きた", "meaning": "北 / 北方", "example": "北へ行きます。(向北走。)" },
  { "level": "N5", "main": "ギター", "kana": "ギター", "meaning": "吉他", "example": "ギターを弾くのが好きです。(喜欢弹吉他。)" },
  { "level": "N5", "main": "汚い", "kana": "きたない", "meaning": "脏", "example": "手が汚いので洗います。(手脏了，所以要洗。)" },
  { "level": "N5", "main": "喫茶店", "kana": "きっさてん", "meaning": "咖啡馆", "example": "喫茶店でコーヒーを飲みました。(在咖啡馆喝了咖啡。)" },
  { "level": "N5", "main": "切手", "kana": "きって", "meaning": "邮票", "example": "郵便局で切手を買います。(在邮局买邮票。)" },
  { "level": "N5", "main": "切符", "kana": "きっぷ", "meaning": "车票", "example": "電車の切符をなくしました。(弄丢了电车票。)" },
  { "level": "N5", "main": "昨日", "kana": "きのう", "meaning": "昨天", "example": "昨日は雨でした。(昨天是雨天。)" },
  { "level": "N5", "main": "牛肉", "kana": "ぎゅうにく", "meaning": "牛肉", "example": "今日の晩ご飯は牛肉です。(今天的晚饭是牛肉。)" },
  { "level": "N5", "main": "牛乳", "kana": "ぎゅうにゅう", "meaning": "牛奶", "example": "毎朝、牛乳を飲みます。(每天早上喝牛奶。)" },
  { "level": "N5", "main": "教室", "kana": "きょうしつ", "meaning": "教室", "example": "教室に学生がいます。(教室里有学生。)" },
  { "level": "N5", "main": "兄弟", "kana": "きょうだい", "meaning": "兄弟姐妹", "example": "兄弟は何人ですか。(兄弟姐妹有几个人？)" },
  { "level": "N5", "main": "去年", "kana": "きょねん", "meaning": "去年", "example": "去年、日本へ来ました。(去年来了日本。)" },
  { "level": "N5", "main": "嫌い", "kana": "きらい", "meaning": "讨厌", "example": "私は納豆が嫌いです。(我讨厌纳豆。)" },
  { "level": "N5", "main": "切る", "kana": "きる", "meaning": "切 / 剪", "example": "はさみで紙を切ります。(用剪刀剪纸。)" },
  { "level": "N5", "main": "着る", "kana": "きる", "meaning": "穿 (上身)", "example": "シャツを着ます。(穿衬衫。)" },
  { "level": "N5", "main": "きれい", "kana": "きれい", "meaning": "漂亮 / 干净", "example": "この花はきれいですね。(这花真漂亮啊。)" },
  { "level": "N5", "main": "キログラム", "kana": "キログラム", "meaning": "千克 / 公斤", "example": "体重は50キログラムです。(体重是50公斤。)" },
  { "level": "N5", "main": "キロメートル", "kana": "キロメートル", "meaning": "千米 / 公里", "example": "ここから駅まで2キロメートルです。(从这里到车站是2公里。)" },
  { "level": "N5", "main": "銀行", "kana": "ぎんこう", "meaning": "银行", "example": "銀行へお金を出しに行きます。(去银行取钱。)" },
  { "level": "N5", "main": "金曜日", "kana": "きんようび", "meaning": "星期五", "example": "金曜日の夜は飲みに行きます。(星期五晚上去喝酒。)" },
  { "level": "N5", "main": "薬", "kana": "くすり", "meaning": "药", "example": "頭が痛いので薬を飲みます。(因为头痛所以吃药。)" },
  { "level": "N5", "main": "ください", "kana": "ください", "meaning": "请给 / 请做", "example": "水をください。(请给我水。)" },
  { "level": "N5", "main": "果物", "kana": "くだもの", "meaning": "水果", "example": "好きな果物はりんごです。(喜欢的水果是苹果。)" },
  { "level": "N5", "main": "口", "kana": "くち", "meaning": "嘴", "example": "口を大きく開けてください。(请把嘴张大。)" },
  { "level": "N5", "main": "靴", "kana": "くつ", "meaning": "鞋子", "example": "新しい靴を買いました。(买了新鞋子。)" },
  { "level": "N5", "main": "靴下", "kana": "くつした", "meaning": "袜子", "example": "靴下を履きます。(穿袜子。)" },
  { "level": "N5", "main": "国", "kana": "くに", "meaning": "国家 / 故乡", "example": "お国はどちらですか。(你是哪个国家的？)" },
  { "level": "N5", "main": "曇り", "kana": "くもり", "meaning": "阴天", "example": "今日は曇りです。(今天是阴天。)" },
  { "level": "N5", "main": "曇る", "kana": "くもる", "meaning": "变阴天", "example": "午後から曇るでしょう。(下午可能会变阴天。)" },
  { "level": "N5", "main": "暗い", "kana": "くらい", "meaning": "暗 / 黑暗", "example": "部屋が暗いです。(房间很暗。)" },
  { "level": "N5", "main": "クラス", "kana": "クラス", "meaning": "班级", "example": "クラスに留学生がいます。(班里有留学生。)" },
  { "level": "N5", "main": "グラム", "kana": "グラム", "meaning": "克", "example": "お肉を200グラムください。(请给我200克肉。)" },
  { "level": "N5", "main": "車", "kana": "くるま", "meaning": "车 / 汽车", "example": "父は車を持っています。(父亲有车。)" },
  { "level": "N5", "main": "黒", "kana": "くろ", "meaning": "黑色", "example": "黒が好きです。(我喜欢黑色。)" },
  { "level": "N5", "main": "黒い", "kana": "くろい", "meaning": "黑色的", "example": "黒い猫がいます。(有一只黑猫。)" },
  { "level": "N5", "main": "警官", "kana": "けいかん", "meaning": "警官 / 警察", "example": "あそこに警官がいます。(那里有警察。)" },
  { "level": "N5", "main": "今朝", "kana": "けさ", "meaning": "今天早上", "example": "今朝は早く起きました。(今天早上起得很早。)" },
  { "level": "N5", "main": "消す", "kana": "けす", "meaning": "关闭 (电器) / 擦掉", "example": "テレビを消してください。(请关掉电视。)" },
  { "level": "N5", "main": "結構", "kana": "けっこう", "meaning": "很好 / 足够了 (用于拒绝)", "example": "いいえ、結構です。(不用了，谢谢。)" },
  { "level": "N5", "main": "結婚", "kana": "けっこん", "meaning": "结婚", "example": "来年、結婚します。(明年结婚。)" },
  { "level": "N5", "main": "月曜日", "kana": "げつようび", "meaning": "星期一", "example": "月曜日から働きます。(从星期一开始工作。)" },
  { "level": "N5", "main": "玄関", "kana": "げんかん", "meaning": "玄关 / 门口", "example": "玄関で靴を脱ぎます。(在玄关脱鞋。)" },
  { "level": "N5", "main": "元気", "kana": "げんき", "meaning": "健康 / 有精神", "example": "お元気ですか。(你好吗？/身体好吗？)" },
  { "level": "N5", "main": "五", "kana": "ご", "meaning": "五", "example": "りんごが五つあります。(有五个苹果。)" },
  { "level": "N5", "main": "公園", "kana": "こうえん", "meaning": "公园", "example": "公園で散歩します。(在公园散步。)" },
  { "level": "N5", "main": "交差点", "kana": "こうさてん", "meaning": "十字路口", "example": "交差点を右に曲がります。(在十字路口向右拐。)" },
  { "level": "N5", "main": "紅茶", "kana": "こうちゃ", "meaning": "红茶", "example": "ミルクを入れて紅茶を飲みます。(加牛奶喝红茶。)" },
  { "level": "N5", "main": "交番", "kana": "こうばん", "meaning": "派出所 / 岗亭", "example": "交番で道を聞きました。(在派出所问了路。)" },
  { "level": "N5", "main": "声", "kana": "こえ", "meaning": "声音", "example": "彼女は声がきれいです。(她的声音很好听。)" },
  { "level": "N5", "main": "コート", "kana": "コート", "meaning": "外套 / 大衣", "example": "寒いのでコートを着ます。(因为冷，穿上大衣。)" },
  { "level": "N5", "main": "コーヒー", "kana": "コーヒー", "meaning": "咖啡", "example": "朝はコーヒーを飲みます。(早上喝咖啡。)" },
  { "level": "N5", "main": "午後", "kana": "ごご", "meaning": "下午", "example": "午後から雨が降ります。(下午会下雨。)" },
  { "level": "N5", "main": "九日", "kana": "ここのか", "meaning": "九号 / 九天", "example": "来月の九日に日本へ行きます。(下个月九号去日本。)" },
  { "level": "N5", "main": "九つ", "kana": "ここのつ", "meaning": "九个", "example": "みかんが九つあります。(有九个橘子。)" },
  { "level": "N5", "main": "午前", "kana": "ごぜん", "meaning": "上午", "example": "会議は午前9時からです。(会议上午9点开始。)" },
  { "level": "N5", "main": "答える", "kana": "こたえる", "meaning": "回答", "example": "先生の質問に答えます。(回答老师的问题。)" },
  { "level": "N5", "main": "こちら", "kana": "こちら", "meaning": "这边 / 这位 (礼貌)", "example": "こちらが田中さんです。(这位是田中先生。)" },
  { "level": "N5", "main": "こっち", "kana": "こっち", "meaning": "这边 (口语)", "example": "こっちに来てください。(请到这边来。)" },
  { "level": "N5", "main": "コップ", "kana": "コップ", "meaning": "杯子", "example": "コップで水を飲みます。(用杯子喝水。)" },
  { "level": "N5", "main": "今年", "kana": "ことし", "meaning": "今年", "example": "今年は良い年でした。(今年是好的一年。)" },
  { "level": "N5", "main": "言葉", "kana": "ことば", "meaning": "语言 / 词汇 / 话语", "example": "日本の言葉を勉強します。(学习日本的语言。)" },
  { "level": "N5", "main": "子供", "kana": "こども", "meaning": "小孩 / 儿童", "example": "公園で子供が遊んでいます。(孩子在公园玩。)" },
  { "level": "N5", "main": "御飯", "kana": "ごはん", "meaning": "饭 / 米饭", "example": "朝御飯を食べましたか。(吃过早饭了吗？)" },
  { "level": "N5", "main": "困る", "kana": "こまる", "meaning": "为难 / 困扰", "example": "お金がなくて困っています。(没有钱，很困扰。)" },
  { "level": "N5", "main": "これ", "kana": "これ", "meaning": "这个", "example": "これは私のペンです。(这是我的笔。)" },
  { "level": "N5", "main": "今月", "kana": "こんげつ", "meaning": "这个月", "example": "今月は忙しいです。(这个月很忙。)" },
  { "level": "N5", "main": "今週", "kana": "こんしゅう", "meaning": "这周", "example": "今週の土曜日は暇です。(这周六有空。)" },
  { "level": "N5", "main": "こんな", "kana": "こんな", "meaning": "这样的", "example": "こんな難しい本は読めません。(这么难的书我读不了。)" },
  { "level": "N5", "main": "今晩", "kana": "こんばん", "meaning": "今晚", "example": "今晩、カレーを食べます。(今晚吃咖喱。)" },
  { "level": "N5", "main": "さあ", "kana": "さあ", "meaning": "那么... / 哎呀... (用于催促或犹豫)", "example": "さあ、行きましょう。(来，走吧。)" },
  { "level": "N5", "main": "財布", "kana": "さいふ", "meaning": "钱包", "example": "かばんに財布を入れます。(把钱包放进包里。)" },
  { "level": "N5", "main": "先", "kana": "さき", "meaning": "先 / 前头", "example": "お先に失礼します。(我先告辞了。)" },
  { "level": "N5", "main": "咲く", "kana": "さく", "meaning": "开花", "example": "庭に桜が咲きました。(院子里的樱花开了。)" },
  { "level": "N5", "main": "作文", "kana": "さくぶん", "meaning": "作文", "example": "日本語で作文を書きます。(用日语写作文。)" },
  { "level": "N5", "main": "差す", "kana": "さす", "meaning": "撑 (伞)", "example": "雨なので傘を差します。(因为下雨，所以撑伞。)" },
  { "level": "N5", "main": "雑誌", "kana": "ざっし", "meaning": "杂志", "example": "本屋で雑誌を買いました。(在书店买了杂志。)" },
  { "level": "N5", "main": "砂糖", "kana": "さとう", "meaning": "糖 / 砂糖", "example": "コーヒーに砂糖を入れますか。(咖啡里加糖吗？)" },
  { "level": "N5", "main": "寒い", "kana": "さむい", "meaning": "寒冷", "example": "今日はとても寒いです。(今天非常冷。)" },
  { "level": "N5", "main": "さ来年", "kana": "さらいねん", "meaning": "后年", "example": "さ来年、大学を卒業します。(后年大学毕业。)" },
  { "level": "N5", "main": "しかし", "kana": "しかし", "meaning": "但是", "example": "行きたいです。しかし、時間がありません。(想去。但是没有时间。)" },
  { "level": "N5", "main": "時間", "kana": "じかん", "meaning": "时间", "example": "今、時間がありません。(现在没有时间。)" },
  { "level": "N5", "main": "仕事", "kana": "しごと", "meaning": "工作", "example": "明日は仕事が休みです。(明天工作休息。)" },
  { "level": "N5", "main": "辞書", "kana": "じしょ", "meaning": "字典 / 词典", "example": "わからない言葉を辞書で引きます。(在字典里查不懂的词。)" },
  { "level": "N5", "main": "静か", "kana": "しずか", "meaning": "安静", "example": "図書館は静かです。(图书馆很安静。)" },
  { "level": "N5", "main": "質問", "kana": "しつもん", "meaning": "问题 / 提问", "example": "先生に質問します。(向老师提问。)" },
  { "level": "N5", "main": "自転車", "kana": "じてんしゃ", "meaning": "自行车", "example": "自転車で学校へ行きます。(骑自行车去学校。)" },
  { "level": "N5", "main": "自動車", "kana": "じどうしゃ", "meaning": "汽车", "example": "自動車工場で働いています。(在汽车工厂工作。)" },
  { "level": "N5", "main": "死ぬ", "kana": "しぬ", "meaning": "死", "example": "飼っていた犬が死にました。(养的狗死了。)" },
  { "level": "N5", "main": "字引", "kana": "じびき", "meaning": "字典", "example": "字引を使います。(使用字典。)" },
  { "level": "N5", "main": "自分", "kana": "じぶん", "meaning": "自己", "example": "自分のことは自分でします。(自己的事情自己做。)" },
  { "level": "N5", "main": "閉まる", "kana": "しまる", "meaning": "关闭 / 关着", "example": "店は8時に閉まります。(店8点关门。)" },
  { "level": "N5", "main": "閉める", "kana": "しめる", "meaning": "关闭", "example": "窓を閉めてください。(请关窗。)" },
  { "level": "N5", "main": "締める", "kana": "しめる", "meaning": "系 / 勒紧", "example": "ネクタイを締めます。(系领带。)" },
  { "level": "N5", "main": "じゃ", "kana": "じゃ", "meaning": "那么 (口语)", "example": "じゃ、また明日。(那么，明天见。)" },
  { "level": "N5", "main": "写真", "kana": "しゃしん", "meaning": "照片", "example": "旅行の写真を撮りました。(拍了旅行的照片。)" },
  { "level": "N5", "main": "シャツ", "kana": "シャツ", "meaning": "衬衫", "example": "白いシャツを着ています。(穿着白衬衫。)" },
  { "level": "N5", "main": "シャワー", "kana": "シャワー", "meaning": "淋浴", "example": "朝、シャワーを浴びます。(早上洗淋浴。)" },
  { "level": "N5", "main": "授業", "kana": "じゅぎょう", "meaning": "课 / 上课", "example": "日本語の授業が始まります。(日语课开始了。)" },
  { "level": "N5", "main": "宿題", "kana": "しゅくだい", "meaning": "作业", "example": "今日は宿題が多いです。(今天作业很多。)" },
  { "level": "N5", "main": "しょうゆ", "kana": "しょうゆ", "meaning": "酱油", "example": "刺身にしょうゆをつけます。(刺身蘸酱油吃。)" },
  { "level": "N5", "main": "食堂", "kana": "しょくどう", "meaning": "食堂", "example": "食堂で昼ご飯を食べます。(在食堂吃午饭。)" },
  { "level": "N5", "main": "知る", "kana": "しる", "meaning": "知道 / 认识", "example": "あの人を知っていますか。(认识那个人吗？)" },
  { "level": "N5", "main": "白", "kana": "しろ", "meaning": "白色", "example": "白が好きです。(喜欢白色。)" },
  { "level": "N5", "main": "白い", "kana": "しろい", "meaning": "白色的", "example": "白い犬がいます。(有一只白色的狗。)" },
  { "level": "N5", "main": "新聞", "kana": "しんぶん", "meaning": "报纸", "example": "父は毎日新聞を読みます。(父亲每天看报纸。)" },
  { "level": "N5", "main": "水曜日", "kana": "すいようび", "meaning": "星期三", "example": "次の水曜日に会いましょう。(下周三见吧。)" },
  { "level": "N5", "main": "吸う", "kana": "すう", "meaning": "吸 (烟) / 呼吸", "example": "ここでたばこを吸ってはいけません。(这里禁止吸烟。)" },
  { "level": "N5", "main": "スカート", "kana": "スカート", "meaning": "裙子", "example": "赤いスカートを買いました。(买了红裙子。)" },
  { "level": "N5", "main": "好き", "kana": "すき", "meaning": "喜欢", "example": "私は猫が好きです。(我喜欢猫。)" },
  { "level": "N5", "main": "少ない", "kana": "すくない", "meaning": "少", "example": "今年は雨が少ないです。(今年雨水少。)" },
  { "level": "N5", "main": "すぐに", "kana": "すぐに", "meaning": "马上 / 立刻", "example": "すぐに行きます。(马上就去。)" },
  { "level": "N5", "main": "少し", "kana": "すこし", "meaning": "一点儿 / 稍微", "example": "お酒を少し飲みました。(喝了一点酒。)" },
  { "level": "N5", "main": "涼しい", "kana": "すずしい", "meaning": "凉爽", "example": "秋は涼しいです。(秋天很凉爽。)" },
  { "level": "N5", "main": "ストーブ", "kana": "ストーブ", "meaning": "炉子 / 暖炉", "example": "寒いのでストーブをつけました。(因为冷，开了暖炉。)" },
  { "level": "N5", "main": "スプーン", "kana": "スプーン", "meaning": "勺子", "example": "スプーンでカレーを食べます。(用勺子吃咖喱。)" },
  { "level": "N5", "main": "スポーツ", "kana": "スポーツ", "meaning": "运动 / 体育", "example": "どんなスポーツが好きですか。(喜欢什么运动？)" },
  { "level": "N5", "main": "ズボン", "kana": "ズボン", "meaning": "裤子", "example": "黒いズボンを履きます。(穿黑裤子。)" },
  { "level": "N5", "main": "住む", "kana": "すむ", "meaning": "居住", "example": "大阪に住んでいます。(住在大阪。)" },
  { "level": "N5", "main": "スリッパ", "kana": "スリッパ", "meaning": "拖鞋", "example": "玄関でスリッパを履いてください。(请在门口换拖鞋。)" },
  { "level": "N5", "main": "する", "kana": "する", "meaning": "做 / 干", "example": "明日、何をしますか。(明天做什么？)" },
  { "level": "N5", "main": "座る", "kana": "すわる", "meaning": "坐", "example": "どうぞ、ここに座ってください。(请坐在这里。)" },
  { "level": "N5", "main": "生徒", "kana": "せいと", "meaning": "学生 (多指中小学生)", "example": "その教室に生徒が３人います。(那个教室里有3个学生。)" },
  { "level": "N5", "main": "セーター", "kana": "セーター", "meaning": "毛衣", "example": "冬はセーターを着ます。(冬天穿毛衣。)" },
  { "level": "N5", "main": "せっけん", "kana": "せっけん", "meaning": "肥皂", "example": "せっけんで手を洗います。(用肥皂洗手。)" },
  { "level": "N5", "main": "背広", "kana": "せびろ", "meaning": "西装", "example": "父は会社へ背広を着て行きます。(父亲穿西装去公司。)" },
  { "level": "N5", "main": "狭い", "kana": "せまい", "meaning": "狭窄", "example": "私の部屋は狭いです。(我的房间很窄。)" },
  { "level": "N5", "main": "ゼロ", "kana": "ゼロ", "meaning": "零", "example": "答えはゼロです。(答案是零。)" },
  { "level": "N5", "main": "千", "kana": "せん", "meaning": "千", "example": "それは千円です。(那个是一千日元。)" },
  { "level": "N5", "main": "先月", "kana": "せんげつ", "meaning": "上个月", "example": "先月、京都へ行きました。(上个月去了京都。)" },
  { "level": "N5", "main": "先週", "kana": "せんしゅう", "meaning": "上周", "example": "先週は忙しかったです。(上周很忙。)" },
  { "level": "N5", "main": "先生", "kana": "せんせい", "meaning": "老师", "example": "田中先生は優しいです。(田中老师很温柔。)" },
  { "level": "N5", "main": "洗濯", "kana": "せんたく", "meaning": "洗衣服", "example": "日曜日に洗濯をします。(星期天洗衣服。)" },
  { "level": "N5", "main": "全部", "kana": "ぜんぶ", "meaning": "全部", "example": "みかんを全部食べました。(把橘子全吃了。)" },
  { "level": "N5", "main": "そちら", "kana": "そちら", "meaning": "那边 (礼貌) / 那个", "example": "そちらは雨ですか。(那边下雨吗？)" },
  { "level": "N5", "main": "そっち", "kana": "そっち", "meaning": "那边 (口语)", "example": "そっちは危ないよ。(那边危险哦。)" },
  { "level": "N5", "main": "そば", "kana": "そば", "meaning": "旁边", "example": "駅のそばに銀行があります。(车站旁边有银行。)" },
  { "level": "N5", "main": "それから", "kana": "それから", "meaning": "然后 / 还有", "example": "勉強しました。それからテレビを見ました。(学习了，然后看了电视。)" },
  { "level": "N5", "main": "それでは", "kana": "それでは", "meaning": "那么", "example": "それでは、始めましょう。(那么，开始吧。)" },
  { "level": "N5", "main": "大学", "kana": "だいがく", "meaning": "大学", "example": "大学で英語を勉強しています。(在大学学习英语。)" },
  { "level": "N5", "main": "大使館", "kana": "たいしかん", "meaning": "大使馆", "example": "ビザを取りに大使館へ行きます。(去大使馆办签证。)" },
  { "level": "N5", "main": "大丈夫", "kana": "だいじょうぶ", "meaning": "没关系 / 不要紧", "example": "時間がありますから、大丈夫です。(有时间，所以没关系。)" },
  { "level": "N5", "main": "大切", "kana": "たいせつ", "meaning": "重要 / 珍贵", "example": "これは大切な本です。(这是很重要的书。)" },
  { "level": "N5", "main": "大好き", "kana": "だいすき", "meaning": "非常喜欢", "example": "私はアニメが大好きです。(我非常喜欢动画。)" },
  { "level": "N5", "main": "台所", "kana": "だいどころ", "meaning": "厨房", "example": "母は台所で料理をしています。(妈妈在厨房做饭。)" },
  { "level": "N5", "main": "たいへん", "kana": "たいへん", "meaning": "非常 / 很 / 够呛", "example": "それはたいへんですね。(那真是够呛啊。)" },
  { "level": "N5", "main": "たくさん", "kana": "たくさん", "meaning": "很多", "example": "本がたくさんあります。(有很多书。)" },
  { "level": "N5", "main": "高い", "kana": "たかい", "meaning": "高 / 贵", "example": "このカメラは高いです。(这个相机很贵。)" },
  { "level": "N5", "main": "出す", "kana": "だす", "meaning": "拿出 / 寄出 / 提交", "example": "ポストに手紙を出しました。(把信投进了邮筒。)" },
  { "level": "N5", "main": "タクシー", "kana": "タクシー", "meaning": "出租车", "example": "タクシーで駅へ行きます。(坐出租车去车站。)" },
  { "level": "N5", "main": "立つ", "kana": "たつ", "meaning": "站立", "example": "ドアの前に立ってください。(请站在门前。)" },
  { "level": "N5", "main": "たて", "kana": "たて", "meaning": "竖 / 纵 / 长", "example": "この紙は縦が20センチです。(这张纸长20厘米。)" },
  { "level": "N5", "main": "建物", "kana": "たてもの", "meaning": "建筑物", "example": "あの白い建物は病院です。(那座白色的建筑物是医院。)" },
  { "level": "N5", "main": "頼む", "kana": "たのむ", "meaning": "请求 / 拜托", "example": "友達に仕事を頼みました。(拜托朋友做工作。)" },
  { "level": "N5", "main": "楽しい", "kana": "たのしい", "meaning": "愉快 / 开心", "example": "旅行はとても楽しかったです。(旅行非常开心。)" },
  { "level": "N5", "main": "たばこ", "kana": "たばこ", "meaning": "香烟", "example": "たばこを吸ってはいけません。(不准吸烟。)" },
  { "level": "N5", "main": "たぶん", "kana": "たぶん", "meaning": "大概 / 可能", "example": "明日はたぶん雨でしょう。(明天大概会下雨。)" },
  { "level": "N5", "main": "食べる", "kana": "たべる", "meaning": "吃", "example": "野菜をたくさん食べます。(吃很多蔬菜。)" },
  { "level": "N5", "main": "食べ物", "kana": "たべもの", "meaning": "食物", "example": "おいしい食べ物が好きです。(喜欢好吃的食物。)" },
  { "level": "N5", "main": "卵", "kana": "たまご", "meaning": "鸡蛋", "example": "卵を２つ買いました。(买了两个鸡蛋。)" },
  { "level": "N5", "main": "誕生日", "kana": "たんじょうび", "meaning": "生日", "example": "誕生日はいつですか。(生日是什么时候？)" },
  { "level": "N5", "main": "だんだん", "kana": "だんだん", "meaning": "渐渐 / 逐渐", "example": "だんだん暖かくなりました。(渐渐变暖和了。)" },
  { "level": "N5", "main": "小さい", "kana": "ちいさい", "meaning": "小", "example": "小さいかばんを持っています。(拿着小包。)" },
  { "level": "N5", "main": "小さな", "kana": "ちいさな", "meaning": "小的 (连体词)", "example": "庭に小さな花があります。(院子里有小花。)" },
  { "level": "N5", "main": "近い", "kana": "ちかい", "meaning": "近", "example": "駅から家まで近いです。(从车站到家很近。)" },
  { "level": "N5", "main": "違う", "kana": "ちがう", "meaning": "不对 / 不同", "example": "いいえ、違います。(不，不对。)" },
  { "level": "N5", "main": "近く", "kana": "ちかく", "meaning": "附近", "example": "学校の近くに住んでいます。(住在学校附近。)" },
  { "level": "N5", "main": "地下鉄", "kana": "ちかてつ", "meaning": "地铁", "example": "地下鉄で会社へ行きます。(坐地铁去公司。)" },
  { "level": "N5", "main": "地図", "kana": "ちず", "meaning": "地图", "example": "地図を見てください。(请看地图。)" },
  { "level": "N5", "main": "茶色", "kana": "ちゃいろ", "meaning": "茶色 / 褐色", "example": "茶色の靴を履いています。(穿着褐色的鞋。)" },
  { "level": "N5", "main": "ちゃわん", "kana": "ちゃわん", "meaning": "碗 / 茶碗", "example": "ちゃわんのご飯を食べます。(吃碗里的饭。)" },
  { "level": "N5", "main": "ちょうど", "kana": "ちょうど", "meaning": "正好", "example": "今、ちょうど３時です。(现在正好3点。)" },
  { "level": "N5", "main": "ちょっと", "kana": "ちょっと", "meaning": "稍微 / 一点", "example": "ちょっと待ってください。(请稍等一下。)" },
  { "level": "N5", "main": "使う", "kana": "つかう", "meaning": "使用", "example": "このパソコンを使ってもいいですか。(可以用这台电脑吗？)" },
  { "level": "N5", "main": "疲れる", "kana": "つかれる", "meaning": "疲劳 / 累", "example": "今日は疲れました。(今天累了。)" },
  { "level": "N5", "main": "着く", "kana": "つく", "meaning": "到达", "example": "3時に駅に着きます。(3点到达车站。)" },
  { "level": "N5", "main": "机", "kana": "つくえ", "meaning": "桌子 / 书桌", "example": "机の上に本があります。(桌子上有书。)" },
  { "level": "N5", "main": "つける", "kana": "つける", "meaning": "打开 (电器) / 点燃", "example": "部屋の電気をつけます。(打开房间的灯。)" },
  { "level": "N5", "main": "勤める", "kana": "つとめる", "meaning": "工作 / 任职", "example": "父は銀行に勤めています。(父亲在银行任职。)" },
  { "level": "N5", "main": "つまらない", "kana": "つまらない", "meaning": "无聊", "example": "この本はつまらないです。(这本书很无聊。)" },
  { "level": "N5", "main": "冷たい", "kana": "つめたい", "meaning": "凉 / 冷 (触感)", "example": "冷たい水が飲みたいです。(想喝冷水。)" },
  { "level": "N5", "main": "強い", "kana": "つよい", "meaning": "强 / 强壮", "example": "今日は風が強いです。(今天风很大。)" },
  { "level": "N5", "main": "手", "kana": "て", "meaning": "手", "example": "ご飯の前に手を洗います。(吃饭前洗手。)" },
  { "level": "N5", "main": "テープ", "kana": "テープ", "meaning": "磁带 / 胶带", "example": "英語のテープを聞きます。(听英语磁带。)" },
  { "level": "N5", "main": "テーブル", "kana": "テーブル", "meaning": "桌子 / 餐桌", "example": "テーブルに皿を置きます。(把盘子放在桌子上。)" },
  { "level": "N5", "main": "テープレコーダー", "kana": "テープレコーダー", "meaning": "录音机", "example": "テープレコーダーを使います。(使用录音机。)" },
  { "level": "N5", "main": "出かける", "kana": "でかける", "meaning": "出门 / 外出", "example": "日曜日はよく出かけます。(星期天经常出门。)" },
  { "level": "N5", "main": "手紙", "kana": "てがみ", "meaning": "信", "example": "母に手紙を書きました。(给妈妈写了信。)" },
  { "level": "N5", "main": "出口", "kana": "でぐち", "meaning": "出口", "example": "出口はあちらです。(出口在那边。)" },
  { "level": "N5", "main": "テスト", "kana": "テスト", "meaning": "考试", "example": "明日は英語のテストがあります。(明天有英语考试。)" },
  { "level": "N5", "main": "デパート", "kana": "デパート", "meaning": "百货商店", "example": "デパートで買い物をします。(在百货商店购物。)" },
  { "level": "N5", "main": "出る", "kana": "でる", "meaning": "出来 / 离开 / 出现", "example": "毎朝８時に家を出ます。(每天早上8点出门。)" },
  { "level": "N5", "main": "テレビ", "kana": "テレビ", "meaning": "电视", "example": "夜、テレビを見ます。(晚上看电视。)" },
  { "level": "N5", "main": "天気", "kana": "てんき", "meaning": "天气", "example": "明日の天気はどうですか。(明天的天气怎么样？)" },
  { "level": "N5", "main": "電気", "kana": "でんき", "meaning": "电 / 电灯", "example": "電気を消してください。(请关灯。)" },
  { "level": "N5", "main": "電車", "kana": "でんしゃ", "meaning": "电车 / 列车", "example": "電車で学校へ行きます。(坐电车去学校。)" },
  { "level": "N5", "main": "電話", "kana": "でんわ", "meaning": "电话", "example": "友達に電話をかけました。(给朋友打了电话。)" },
  { "level": "N5", "main": "ドア", "kana": "ドア", "meaning": "门", "example": "ドアを開けてください。(请把门打开。)" },
  { "level": "N5", "main": "トイレ", "kana": "トイレ", "meaning": "厕所 / 洗手间", "example": "トイレはどこですか。(厕所在哪里？)" },
  { "level": "N5", "main": "どうして", "kana": "どうして", "meaning": "为什么", "example": "どうして来なかったのですか。(为什么没来？)" },
  { "level": "N5", "main": "どうぞ", "kana": "どうぞ", "meaning": "请", "example": "こちらへどうぞ。(请往这边走。)" },
  { "level": "N5", "main": "動物", "kana": "どうぶつ", "meaning": "动物", "example": "動物が好きです。(喜欢动物。)" },
  { "level": "N5", "main": "どうも", "kana": "どうも", "meaning": "谢谢 / 实在 / 好像", "example": "どうもありがとうございます。(非常感谢。)" },
  { "level": "N5", "main": "遠い", "kana": "とおい", "meaning": "远", "example": "学校は家から遠いです。(学校离家很远。)" },
  { "level": "N5", "main": "十日", "kana": "とおか", "meaning": "十号 / 十天", "example": "来月の十日に帰ります。(下个月十号回去。)" },
  { "level": "N5", "main": "時々", "kana": "ときどき", "meaning": "有时", "example": "時々映画を見ます。(有时看电影。)" },
  { "level": "N5", "main": "時計", "kana": "とけい", "meaning": "钟表", "example": "きれいな時計ですね。(漂亮的钟表啊。)" },
  { "level": "N5", "main": "どこ", "kana": "どこ", "meaning": "哪里", "example": "私の本はどこですか。(我的书在哪里？)" },
  { "level": "N5", "main": "所", "kana": "ところ", "meaning": "地方 / 场所", "example": "静かな所へ行きたいです。(想去安静的地方。)" },
  { "level": "N5", "main": "年", "kana": "とし", "meaning": "年纪 / 年", "example": "お年はおいくつですか。(你多大年纪？)" },
  { "level": "N5", "main": "図書館", "kana": "としょかん", "meaning": "图书馆", "example": "図書館で勉強します。(在图书馆学习。)" },
  { "level": "N5", "main": "どちら", "kana": "どちら", "meaning": "哪边 / 哪个 (礼貌)", "example": "お国はどちらですか。(你是哪国人？)" },
  { "level": "N5", "main": "どっち", "kana": "どっち", "meaning": "哪边 / 哪个 (口语)", "example": "どっちが好きですか。(喜欢哪一个？)" },
  { "level": "N5", "main": "とても", "kana": "とても", "meaning": "非常", "example": "今日はとても寒いです。(今天非常冷。)" },
  { "level": "N5", "main": "どなた", "kana": "どなた", "meaning": "哪位 (敬称)", "example": "あの方はどなたですか。(那位是谁？)" },
  { "level": "N5", "main": "隣", "kana": "となり", "meaning": "旁边 / 隔壁", "example": "隣の席に座ってください。(请坐在隔壁座位。)" },
  { "level": "N5", "main": "どの", "kana": "どの", "meaning": "哪个", "example": "どのかばんが欲しいですか。(想要哪个包？)" },
  { "level": "N5", "main": "飛ぶ", "kana": "とぶ", "meaning": "飞", "example": "鳥が空を飛んでいます。(鸟在天上飞。)" },
  { "level": "N5", "main": "友達", "kana": "ともだち", "meaning": "朋友", "example": "友達と遊びます。(和朋友玩。)" },
  { "level": "N5", "main": "土曜日", "kana": "どようび", "meaning": "星期六", "example": "土曜日は休みです。(星期六休息。)" },
  { "level": "N5", "main": "鳥", "kana": "とり", "meaning": "鸟", "example": "木の上に鳥がいます。(树上有鸟。)" },
  { "level": "N5", "main": "とり肉", "kana": "とりにく", "meaning": "鸡肉", "example": "とり肉の料理を作ります。(做鸡肉料理。)" },
  { "level": "N5", "main": "取る", "kana": "とる", "meaning": "拿 / 取", "example": "その本を取ってください。(请把那本书拿给我。)" },
  { "level": "N5", "main": "撮る", "kana": "とる", "meaning": "拍照 / 摄影", "example": "写真を撮りましょう。(拍照片吧。)" },
  { "level": "N5", "main": "ナイフ", "kana": "ナイフ", "meaning": "刀", "example": "ナイフとフォークを使います。(使用刀叉。)" },
  { "level": "N5", "main": "長い", "kana": "ながい", "meaning": "长", "example": "彼女は髪が長いです。(她的头发很长。)" },
  { "level": "N5", "main": "鳴く", "kana": "なく", "meaning": "叫 (动物)", "example": "猫が鳴いています。(猫在叫。)" },
  { "level": "N5", "main": "無くす", "kana": "なくす", "meaning": "弄丢 / 丢失", "example": "財布を無くしました。(把钱包弄丢了。)" },
  { "level": "N5", "main": "なぜ", "kana": "なぜ", "meaning": "为什么", "example": "なぜ泣いているのですか。(为什么在哭？)" },
  { "level": "N5", "main": "夏", "kana": "なつ", "meaning": "夏天", "example": "夏は暑いです。(夏天很热。)" },
  { "level": "N5", "main": "夏休み", "kana": "なつやすみ", "meaning": "暑假", "example": "明日から夏休みです。(明天开始放暑假。)" },
  { "level": "N5", "main": "など", "kana": "など", "meaning": "等等", "example": "本やペンなどを買いました。(买了书和笔等。)" },
  { "level": "N5", "main": "七つ", "kana": "ななつ", "meaning": "七个", "example": "みかんを七つください。(请给我七个橘子。)" },
  { "level": "N5", "main": "名前", "kana": "なまえ", "meaning": "名字", "example": "名前を書いてください。(请写名字。)" },
  { "level": "N5", "main": "習う", "kana": "ならう", "meaning": "学习 (向某人学)", "example": "先生にピアノを習います。(向老师学钢琴。)" },
  { "level": "N5", "main": "並ぶ", "kana": "ならぶ", "meaning": "排队 / 并列", "example": "店に人が並んでいます。(店门口有人在排队。)" },
  { "level": "N5", "main": "並べる", "kana": "ならべる", "meaning": "排列 / 摆放", "example": "机をきれいに並べます。(把桌子排列整齐。)" },
  { "level": "N5", "main": "なる", "kana": "なる", "meaning": "变成 / 成为", "example": "もうすぐ春になります。(马上就要春天了。)" },
  { "level": "N5", "main": "二", "kana": "に", "meaning": "二", "example": "ここにりんごが二つあります。(这里有两个苹果。)" },
  { "level": "N5", "main": "賑やか", "kana": "にぎやか", "meaning": "热闹", "example": "この町は賑やかです。(这个城镇很热闹。)" },
  { "level": "N5", "main": "肉", "kana": "にく", "meaning": "肉", "example": "毎日肉を食べます。(每天吃肉。)" },
  { "level": "N5", "main": "西", "kana": "にし", "meaning": "西 / 西方", "example": "太陽は西に沈みます。(太阳在西方落下。)" },
  { "level": "N5", "main": "日曜日", "kana": "にちようび", "meaning": "星期日", "example": "日曜日は家にいます。(星期天在家里。)" },
  { "level": "N5", "main": "荷物", "kana": "にもつ", "meaning": "行李", "example": "荷物を持ってください。(请拿行李。)" },
  { "level": "N5", "main": "ニュース", "kana": "ニュース", "meaning": "新闻", "example": "テレビでニュースを見ます。(在电视上看新闻。)" },
  { "level": "N5", "main": "庭", "kana": "にわ", "meaning": "院子 / 庭院", "example": "庭にきれいな花があります。(院子里有漂亮的花。)" },
  { "level": "N5", "main": "脱ぐ", "kana": "ぬぐ", "meaning": "脱 (衣、鞋)", "example": "ここで靴を脱いでください。(请在这里脱鞋。)" },
  { "level": "N5", "main": "温い", "kana": "ぬるい", "meaning": "温的 / 不冷不热的 (微温)", "example": "このお茶は少し温いです。(这茶有点温吞。)" },
  { "level": "N5", "main": "ネクタイ", "kana": "ネクタイ", "meaning": "领带", "example": "父にネクタイをプレゼントしました。(送了领带给父亲。)" },
  { "level": "N5", "main": "猫", "kana": "ねこ", "meaning": "猫", "example": "白い猫がいます。(有一只白猫。)" },
  { "level": "N5", "main": "寝る", "kana": "ねる", "meaning": "睡觉", "example": "毎晩10時に寝ます。(每晚10点睡觉。)" },
  { "level": "N5", "main": "ノート", "kana": "ノート", "meaning": "笔记本", "example": "ノートに漢字を書きます。(在笔记本上写汉字。)" },
  { "level": "N5", "main": "登る", "kana": "のぼる", "meaning": "攀登 / 爬", "example": "夏休みに山に登ります。(暑假去爬山。)" },
  { "level": "N5", "main": "飲み物", "kana": "のみもの", "meaning": "饮料", "example": "冷たい飲み物が欲しいです。(想喝冷饮。)" },
  { "level": "N5", "main": "飲む", "kana": "のむ", "meaning": "喝", "example": "コーヒーを飲みます。(喝咖啡。)" },
  { "level": "N5", "main": "乗る", "kana": "のる", "meaning": "乘坐", "example": "駅前でバスに乗ります。(在车站前坐公交车。)" },
  { "level": "N5", "main": "歯", "kana": "は", "meaning": "牙齿", "example": "ご飯の後で歯を磨きます。(饭后刷牙。)" },
  { "level": "N5", "main": "パーティー", "kana": "パーティー", "meaning": "派对 / 聚会", "example": "日曜日にパーティーをします。(星期天举行派对。)" },
  { "level": "N5", "main": "葉書", "kana": "はがき", "meaning": "明信片", "example": "旅行先から葉書を出しました。(在旅行地寄了明信片。)" },
  { "level": "N5", "main": "はく", "kana": "はく", "meaning": "穿 (鞋、裤子)", "example": "新しい靴をはきます。(穿新鞋子。)" },
  { "level": "N5", "main": "箱", "kana": "はこ", "meaning": "箱子 / 盒子", "example": "この箱を開けてください。(请打开这个箱子。)" },
  { "level": "N5", "main": "橋", "kana": "はし", "meaning": "桥", "example": "あの橋を渡りましょう。(过那座桥吧。)" },
  { "level": "N5", "main": "はし", "kana": "はし", "meaning": "筷子", "example": "はしでご飯を食べます。(用筷子吃饭。)" },
  { "level": "N5", "main": "始まる", "kana": "はじまる", "meaning": "开始", "example": "もうすぐ映画が始まります。(电影马上要开始了。)" },
  { "level": "N5", "main": "初め", "kana": "はじめ", "meaning": "开始 / 最初", "example": "夏休みの初めに海へ行きました。(暑假开始的时候去了海边。)" },
  { "level": "N5", "main": "初めて", "kana": "はじめて", "meaning": "第一次", "example": "日本へ来たのは初めてです。(第一次来日本。)" },
  { "level": "N5", "main": "走る", "kana": "はしる", "meaning": "跑", "example": "駅まで走りました。(跑到了车站。)" },
  { "level": "N5", "main": "バス", "kana": "バス", "meaning": "公共汽车 / 巴士", "example": "バスで学校へ通っています。(坐公交车上学。)" },
  { "level": "N5", "main": "バター", "kana": "バター", "meaning": "黄油", "example": "パンにバターを塗ります。(在面包上涂黄油。)" },
  { "level": "N5", "main": "二十歳", "kana": "はたち", "meaning": "20岁", "example": "姉は今年、二十歳になります。(姐姐今年20岁。)" },
  { "level": "N5", "main": "働く", "kana": "はたらく", "meaning": "工作 / 劳动", "example": "父は銀行で働いています。(父亲在银行工作。)" },
  { "level": "N5", "main": "八", "kana": "はち", "meaning": "八", "example": "8時に会いましょう。(8点见吧。)" },
  { "level": "N5", "main": "二十日", "kana": "はつか", "meaning": "20号 / 20天", "example": "来月の二十日は私の誕生日です。(下个月20号是我的生日。)" },
  { "level": "N5", "main": "花", "kana": "はな", "meaning": "花", "example": "きれいな花を買いました。(买了漂亮的花。)" },
  { "level": "N5", "main": "鼻", "kana": "はな", "meaning": "鼻子", "example": "象は鼻が長いです。(大象的鼻子很长。)" },
  { "level": "N5", "main": "話", "kana": "はなし", "meaning": "话 / 故事", "example": "先生の話を聞いてください。(请听老师的话。)" },
  { "level": "N5", "main": "話す", "kana": "はなす", "meaning": "说话 / 讲", "example": "日本語で話しましょう。(用日语说话吧。)" },
  { "level": "N5", "main": "早い", "kana": "はやい", "meaning": "早", "example": "今日は学校へ行くのが早いです。(今天去学校很早。)" },
  { "level": "N5", "main": "速い", "kana": "はやい", "meaning": "快", "example": "新幹線は速いです。(新干线很快。)" },
  { "level": "N5", "main": "春", "kana": "はる", "meaning": "春天", "example": "春は桜が咲きます。(春天樱花盛开。)" },
  { "level": "N5", "main": "貼る", "kana": "はる", "meaning": "贴", "example": "封筒に切手を貼ります。(在信封上贴邮票。)" },
  { "level": "N5", "main": "晴れ", "kana": "はれ", "meaning": "晴天", "example": "今日はいい晴れですね。(今天天气真晴朗啊。)" },
  { "level": "N5", "main": "晴れる", "kana": "はれる", "meaning": "放晴", "example": "午後から晴れるでしょう。(下午可能会放晴。)" },
  { "level": "N5", "main": "半", "kana": "はん", "meaning": "半", "example": "今、9時半です。(现在9点半。)" },
  { "level": "N5", "main": "晩", "kana": "ばん", "meaning": "晚上", "example": "昨日の晩、本を読みました。(昨晚看了书。)" },
  { "level": "N5", "main": "パン", "kana": "パン", "meaning": "面包", "example": "毎朝、パンを食べます。(每天早上吃面包。)" },
  { "level": "N5", "main": "ハンカチ", "kana": "ハンカチ", "meaning": "手帕", "example": "ハンカチで手を拭きます。(用手帕擦手。)" },
  { "level": "N5", "main": "番号", "kana": "ばんごう", "meaning": "号码", "example": "電話番号を教えてください。(请告诉我电话号码。)" },
  { "level": "N5", "main": "晩御飯", "kana": "ばんごはん", "meaning": "晚饭", "example": "晩御飯にカレーを食べました。(晚饭吃了咖喱。)" },
  { "level": "N5", "main": "半分", "kana": "はんぶん", "meaning": "一半", "example": "ケーキを半分食べました。(吃了一半蛋糕。)" },
  { "level": "N5", "main": "引く", "kana": "ひく", "meaning": "拉 / 查 (字典)", "example": "辞書を引いて言葉の意味を調べます。(查字典了解词义。)" },
  { "level": "N5", "main": "低い", "kana": "ひくい", "meaning": "低 / 矮", "example": "あの山は低いです。(那座山很矮。)" },
  { "level": "N5", "main": "飛行機", "kana": "ひこうき", "meaning": "飞机", "example": "飛行機で旅行に行きます。(坐飞机去旅行。)" },
  { "level": "N5", "main": "左", "kana": "ひだり", "meaning": "左", "example": "次の角を左に曲がります。(下一个路口向左拐。)" },
  { "level": "N5", "main": "一つ", "kana": "ひとつ", "meaning": "一个", "example": "質問が一つあります。(有一个问题。)" },
  { "level": "N5", "main": "一月", "kana": "いちがつ", "meaning": "一月", "example": "一月はとても寒いです。(一月非常冷。)" },
  { "level": "N5", "main": "百", "kana": "ひゃく", "meaning": "百", "example": "百円玉を持っていますか。(有百元硬币吗？)" },
  { "level": "N5", "main": "病院", "kana": "びょういん", "meaning": "医院", "example": "病気ですから、病院へ行きます。(因为生病，去医院。)" },
  { "level": "N5", "main": "病気", "kana": "びょうき", "meaning": "生病 / 疾病", "example": "母は病気です。(妈妈生病了。)" },
  { "level": "N5", "main": "昼", "kana": "ひる", "meaning": "中午 / 白天", "example": "昼から雨が降るでしょう。(中午开始可能会下雨。)" },
  { "level": "N5", "main": "昼御飯", "kana": "ひるごはん", "meaning": "午饭", "example": "一緒に昼御飯を食べませんか。(一起吃午饭吗？)" },
  { "level": "N5", "main": "広い", "kana": "ひろい", "meaning": "宽敞 / 广阔", "example": "私の部屋は広いです。(我的房间很宽敞。)" },
  { "level": "N5", "main": "フィルム", "kana": "フィルム", "meaning": "胶卷 / 胶片", "example": "カメラにフィルムを入れます。(给相机装胶卷。)" },
  { "level": "N5", "main": "封筒", "kana": "ふうとう", "meaning": "信封", "example": "手紙を封筒に入れます。(把信放进信封。)" },
  { "level": "N5", "main": "プール", "kana": "プール", "meaning": "游泳池", "example": "夏はプールで泳ぎます。(夏天在游泳池游泳。)" },
  { "level": "N5", "main": "フォーク", "kana": "フォーク", "meaning": "叉子", "example": "フォークでパスタを食べます。(用叉子吃意面。)" },
  { "level": "N5", "main": "吹く", "kana": "ふく", "meaning": "吹 (风)", "example": "強い風が吹いています。(正刮着大风。)" },
  { "level": "N5", "main": "服", "kana": "ふく", "meaning": "衣服", "example": "新しい服を買いました。(买了新衣服。)" },
  { "level": "N5", "main": "二つ", "kana": "ふたつ", "meaning": "两个", "example": "質問が二つあります。(有两个问题。)" },
  { "level": "N5", "main": "豚肉", "kana": "ぶたにく", "meaning": "猪肉", "example": "豚肉の料理が好きです。(喜欢猪肉料理。)" },
  { "level": "N5", "main": "二日", "kana": "ふつか", "meaning": "二号 / 两天", "example": "来月の二日に会います。(下个月二号见面。)" },
  { "level": "N5", "main": "太い", "kana": "ふとい", "meaning": "粗 / 胖", "example": "彼の足は太いです。(他的腿很粗。)" },
  { "level": "N5", "main": "冬", "kana": "ふゆ", "meaning": "冬天", "example": "日本の冬は寒いです。(日本的冬天很冷。)" },
  { "level": "N5", "main": "降る", "kana": "ふる", "meaning": "下 (雨、雪)", "example": "明日、雨が降るでしょう。(明天可能会下雨。)" },
  { "level": "N5", "main": "古い", "kana": "ふるい", "meaning": "旧 / 老", "example": "これは古い時計です。(这是旧钟表。)" },
  { "level": "N5", "main": "ふろ", "kana": "ふろ", "meaning": "澡堂 / 浴缸", "example": "おふろに入ります。(洗澡。)" },
  { "level": "N5", "main": "文章", "kana": "ぶんしょう", "meaning": "文章 / 句子", "example": "日本語の文章を書きます。(写日语文章。)" },
  { "level": "N5", "main": "ページ", "kana": "ページ", "meaning": "页", "example": "教科書の10ページを開けてください。(请翻开课本第10页。)" },
  { "level": "N5", "main": "下手", "kana": "へた", "meaning": "笨拙 / 不擅长", "example": "私は絵が下手です。(我不擅长画画。)" },
  { "level": "N5", "main": "ベッド", "kana": "ベッド", "meaning": "床", "example": "ベッドで寝ます。(在床上睡觉。)" },
  { "level": "N5", "main": "ペット", "kana": "ペット", "meaning": "宠物", "example": "ペットを飼っていますか。(养宠物了吗？)" },
  { "level": "N5", "main": "部屋", "kana": "へや", "meaning": "房间", "example": "ここは私の部屋です。(这里是我的房间。)" },
  { "level": "N5", "main": "辺", "kana": "へん", "meaning": "一带 / 附近", "example": "この辺にコンビニはありますか。(这附近有便利店吗？)" },
  { "level": "N5", "main": "ペン", "kana": "ペン", "meaning": "笔 / 钢笔", "example": "ペンを貸してください。(请借给我笔。)" },
  { "level": "N5", "main": "便利", "kana": "べんり", "meaning": "方便", "example": "この辞書は便利です。(这本字典很方便。)" },
  { "level": "N5", "main": "帽子", "kana": "ぼうし", "meaning": "帽子", "example": "白い帽子をかぶります。(戴白帽子。)" },
  { "level": "N5", "main": "ボールペン", "kana": "ボールペン", "meaning": "圆珠笔", "example": "黒いボールペンで書いてください。(请用黑色圆珠笔写。)" },
  { "level": "N5", "main": "ほか", "kana": "ほか", "meaning": "其他 / 另外", "example": "ほかの色がありますか。(有其他颜色吗？)" },
  { "level": "N5", "main": "ポケット", "kana": "ポケット", "meaning": "口袋", "example": "ポケットにハンカチを入れます。(把手帕放进口袋。)" },
  { "level": "N5", "main": "欲しい", "kana": "ほしい", "meaning": "想要", "example": "新しいカメラが欲しいです。(想要新相机。)" },
  { "level": "N5", "main": "ポスト", "kana": "ポスト", "meaning": "邮筒 / 邮箱", "example": "手紙をポストに入れます。(把信投进邮筒。)" },
  { "level": "N5", "main": "細い", "kana": "ほそい", "meaning": "细 / 瘦", "example": "指が細いです。(手指很细。)" },
  { "level": "N5", "main": "ボタン", "kana": "ボタン", "meaning": "纽扣 / 按钮", "example": "シャツのボタンが取れました。(衬衫的扣子掉了。)" },
  { "level": "N5", "main": "ホテル", "kana": "ホテル", "meaning": "酒店 / 旅馆", "example": "ホテルを予約しました。(预订了酒店。)" },
  { "level": "N5", "main": "本", "kana": "ほん", "meaning": "书", "example": "本を読みます。(看书。)" },
  { "level": "N5", "main": "本棚", "kana": "ほんだな", "meaning": "书架", "example": "本棚に本を並べます。(把书摆在书架上。)" },
  { "level": "N5", "main": "ほんとう", "kana": "ほんとう", "meaning": "真的", "example": "それは本当ですか。(那是真的吗？)" },
  { "level": "N5", "main": "毎朝", "kana": "まいあさ", "meaning": "每天早上", "example": "毎朝コーヒーを飲みます。(每天早上喝咖啡。)" },
  { "level": "N5", "main": "毎月", "kana": "まいつき", "meaning": "每个月", "example": "毎月、貯金をします。(每个月都存钱。)" },
  { "level": "N5", "main": "毎週", "kana": "まいしゅう", "meaning": "每周", "example": "毎週テニスをします。(每周打网球。)" },
  { "level": "N5", "main": "毎日", "kana": "まいにち", "meaning": "每天", "example": "毎日日本語を勉強します。(每天学习日语。)" },
  { "level": "N5", "main": "毎年", "kana": "まいとし", "meaning": "每年", "example": "毎年、海外へ行きます。(每年去国外。)" },
  { "level": "N5", "main": "毎晩", "kana": "まいばん", "meaning": "每天晚上", "example": "毎晩テレビを見ます。(每晚看电视。)" },
  { "level": "N5", "main": "曲る", "kana": "まがる", "meaning": "拐弯 / 曲折", "example": "次の角を右に曲がってください。(请在下一个路口向右拐。)" },
  { "level": "N5", "main": "まずい", "kana": "まずい", "meaning": "难吃 / 糟糕", "example": "この料理はまずいです。(这道菜很难吃。)" },
  { "level": "N5", "main": "また", "kana": "また", "meaning": "又 / 再", "example": "また明日会いましょう。(明天再见。)" },
  { "level": "N5", "main": "まだ", "kana": "まだ", "meaning": "还没有 / 尚", "example": "まだご飯を食べていません。(还没吃饭。)" },
  { "level": "N5", "main": "町", "kana": "まち", "meaning": "城镇 / 街道", "example": "きれいな町ですね。(漂亮的城镇啊。)" },
  { "level": "N5", "main": "待つ", "kana": "まつ", "meaning": "等待", "example": "ここで友達を待ちます。(在这里等朋友。)" },
  { "level": "N5", "main": "まっすぐ", "kana": "まっすぐ", "meaning": "笔直 / 径直", "example": "この道をまっすぐ行きます。(顺着这条路直走。)" },
  { "level": "N5", "main": "マッチ", "kana": "マッチ", "meaning": "火柴", "example": "マッチで火をつけます。(用火柴点火。)" },
  { "level": "N5", "main": "窓", "kana": "まど", "meaning": "窗户", "example": "暑いので窓を開けました。(因为热，打开了窗户。)" },
  { "level": "N5", "main": "万年筆", "kana": "まんねんひつ", "meaning": "钢笔", "example": "父に万年筆をもらいました。(收到了父亲送的钢笔。)" },
  { "level": "N5", "main": "磨く", "kana": "みがく", "meaning": "刷 / 磨", "example": "毎晩、歯を磨きます。(每晚刷牙。)" },
  { "level": "N5", "main": "右", "kana": "みぎ", "meaning": "右", "example": "右の手を上げてください。(请举右手。)" },
  { "level": "N5", "main": "短い", "kana": "みじかい", "meaning": "短", "example": "彼女は髪が短いです。(她的头发很短。)" },
  { "level": "N5", "main": "水", "kana": "みず", "meaning": "水", "example": "水を一杯ください。(请给我一杯水。)" },
  { "level": "N5", "main": "見せる", "kana": "みせる", "meaning": "给...看", "example": "その写真を見せてください。(请给我看那张照片。)" },
  { "level": "N5", "main": "道", "kana": "みち", "meaning": "道路", "example": "この道を歩きます。(走这条路。)" },
  { "level": "N5", "main": "三日", "kana": "みっか", "meaning": "三号 / 三天", "example": "三日に日本へ来ました。(三号来了日本。)" },
  { "level": "N5", "main": "三つ", "kana": "みっつ", "meaning": "三个", "example": "りんごが三つあります。(有三个苹果。)" },
  { "level": "N5", "main": "緑", "kana": "みどり", "meaning": "绿色", "example": "山が緑できれいです。(山是绿色的，很美。)" },
  { "level": "N5", "main": "皆さん", "kana": "みなさん", "meaning": "大家 / 各位", "example": "皆さん、こんにちは。(大家好。)" },
  { "level": "N5", "main": "耳", "kana": "みみ", "meaning": "耳朵", "example": "耳が少し痛いです。(耳朵有点痛。)" },
  { "level": "N5", "main": "観る", "kana": "みる", "meaning": "观看", "example": "明日、映画を観ます。(明天看电影。)" },
  { "level": "N5", "main": "みんな", "kana": "みんな", "meaning": "大家 / 全体", "example": "みんなで歌を歌いました。(大家一起唱了歌。)" },
  { "level": "N5", "main": "六日", "kana": "むいか", "meaning": "六号 / 六天", "example": "来月の六日は休みです。(下个月六号休息。)" },
  { "level": "N5", "main": "向こう", "kana": "むこう", "meaning": "对面 / 那边", "example": "川の向こうに家があります。(河对面有房子。)" },
  { "level": "N5", "main": "難しい", "kana": "むずかしい", "meaning": "困难 / 难", "example": "日本語は難しいですが、楽しいです。(日语虽然难，但很有趣。)" },
  { "level": "N5", "main": "六つ", "kana": "むっつ", "meaning": "六个", "example": "卵を六つ買いました。(买了六个鸡蛋。)" },
  { "level": "N5", "main": "村", "kana": "むら", "meaning": "村庄", "example": "静かな村に住んでいます。(住在安静的村庄。)" },
  { "level": "N5", "main": "目", "kana": "め", "meaning": "眼睛", "example": "目が大きくてかわいいです。(眼睛大大的，很可爱。)" },
  { "level": "N5", "main": "メートル", "kana": "メートル", "meaning": "米 (单位)", "example": "駅から500メートル歩きます。(从车站走500米。)" },
  { "level": "N5", "main": "もう", "kana": "もう", "meaning": "已经 / 再", "example": "もう宿題をしました。(已经做完作业了。)" },
  { "level": "N5", "main": "もう一度", "kana": "もういちど", "meaning": "再一次", "example": "もう一度言ってください。(请再说一次。)" },
  { "level": "N5", "main": "木曜日", "kana": "もくようび", "meaning": "星期四", "example": "木曜日は図書館へ行きます。(星期四去图书馆。)" },
  { "level": "N5", "main": "持つ", "kana": "もつ", "meaning": "拿 / 拥有", "example": "荷物を持ちましょうか。(我来拿行李吧？)" },
  { "level": "N5", "main": "もっと", "kana": "もっと", "meaning": "更加", "example": "もっとゆっくり話してください。(请说得更慢一点。)" },
  { "level": "N5", "main": "物", "kana": "もの", "meaning": "物品 / 东西", "example": "甘い物が食べたいです。(想吃甜食。)" },
  { "level": "N5", "main": "問題", "kana": "もんだい", "meaning": "问题", "example": "この問題はわかりません。(这个问题不懂。)" },
  { "level": "N5", "main": "八百屋", "kana": "やおや", "meaning": "蔬菜店", "example": "八百屋で野菜を買います。(在蔬菜店买菜。)" },
  { "level": "N5", "main": "野菜", "kana": "やさい", "meaning": "蔬菜", "example": "毎日野菜を食べます。(每天吃蔬菜。)" },
  { "level": "N5", "main": "易しい", "kana": "やさしい", "meaning": "容易 / 简单", "example": "この本は易しいです。(这本书很简单。)" },
  { "level": "N5", "main": "安い", "kana": "やすい", "meaning": "便宜", "example": "この店はとても安いです。(这家店非常便宜。)" },
  { "level": "N5", "main": "休み", "kana": "やすみ", "meaning": "休息 / 假期", "example": "明日は学校が休みです。(明天学校休息。)" },
  { "level": "N5", "main": "休む", "kana": "やすむ", "meaning": "休息 / 请假", "example": "疲れたので少し休みます。(累了所以休息一下。)" },
  { "level": "N5", "main": "八つ", "kana": "やっつ", "meaning": "八个", "example": "みかんが八つあります。(有八个橘子。)" },
  { "level": "N5", "main": "山", "kana": "やま", "meaning": "山", "example": "富士山は高い山です。(富士山是座高山。)" },
  { "level": "N5", "main": "やる", "kana": "やる", "meaning": "做 / 干 / 给 (对下级/动植物)", "example": "花に水をやります。(给花浇水。)" },
  { "level": "N5", "main": "夕方", "kana": "ゆうがた", "meaning": "傍晚", "example": "夕方、雨が降りました。(傍晚下了雨。)" },
  { "level": "N5", "main": "夕飯", "kana": "ゆうはん", "meaning": "晚饭", "example": "夕飯は何を食べましたか。(晚饭吃了什么？)" },
  { "level": "N5", "main": "郵便局", "kana": "ゆうびんきょく", "meaning": "邮局", "example": "郵便局で切手を買います。(在邮局买邮票。)" },
  { "level": "N5", "main": "昨夜", "kana": "ゆうべ", "meaning": "昨晚", "example": "昨夜は遅く帰りました。(昨晚回去得很晚。)" },
  { "level": "N5", "main": "有名", "kana": "ゆうめい", "meaning": "有名", "example": "あの人は有名な歌手です。(那个人是有名的歌手。)" },
  { "level": "N5", "main": "雪", "kana": "ゆき", "meaning": "雪", "example": "外は雪が降っています。(外面正在下雪。)" },
  { "level": "N5", "main": "ゆっくり", "kana": "ゆっくり", "meaning": "慢慢地 / 舒适地", "example": "どうぞ、ゆっくりしてください。(请慢慢来/请放松。)" },
  { "level": "N5", "main": "八日", "kana": "ようか", "meaning": "八号 / 八天", "example": "来月の八日は日曜日です。(下个月八号是星期天。)" },
  { "level": "N5", "main": "洋服", "kana": "ようふく", "meaning": "西式服装 / 衣服", "example": "きれいな洋服を買いました。(买了漂亮的衣服。)" },
  { "level": "N5", "main": "よく", "kana": "よく", "meaning": "经常 / 很好地", "example": "私はよく映画を見ます。(我经常看电影。)" },
  { "level": "N5", "main": "横", "kana": "よこ", "meaning": "旁边 / 横", "example": "銀行の横に郵便局があります。(银行旁边有邮局。)" },
  { "level": "N5", "main": "四日", "kana": "よっか", "meaning": "四号 / 四天", "example": "四日に友達に会います。(四号见朋友。)" },
  { "level": "N5", "main": "四つ", "kana": "よっつ", "meaning": "四个", "example": "いすを四つ並べてください。(请摆四把椅子。)" },
  { "level": "N5", "main": "呼ぶ", "kana": "よぶ", "meaning": "呼叫 / 邀请", "example": "タクシーを呼んでください。(请叫辆出租车。)" },
  { "level": "N5", "main": "読む", "kana": "よむ", "meaning": "读 / 阅读", "example": "毎晩、本を読みます。(每晚读书。)" },
  { "level": "N5", "main": "弱い", "kana": "よわい", "meaning": "弱 / 软弱", "example": "私は体が弱いです。(我身体很弱。)" },
  { "level": "N5", "main": "来月", "kana": "らいげつ", "meaning": "下个月", "example": "来月、国へ帰ります。(下个月回国。)" },
  { "level": "N5", "main": "来週", "kana": "らいしゅう", "meaning": "下周", "example": "来週は忙しいです。(下周很忙。)" },
  { "level": "N5", "main": "来年", "kana": "らいねん", "meaning": "明年", "example": "来年、日本へ行きます。(明年去日本。)" },
  { "level": "N5", "main": "ラジオ", "kana": "ラジオ", "meaning": "收音机", "example": "ラジオでニュースを聞きます。(用收音机听新闻。)" },
  { "level": "N5", "main": "ラジカセ", "kana": "ラジカセ", "meaning": "收录机", "example": "古いラジカセを持っています。(有一台旧的收录机。)" },
  { "level": "N5", "main": "ラジオカセット", "kana": "ラジオカセット", "meaning": "收录机", "example": "ラジオカセットで音楽を聞きます。(用收录机听音乐。)" },
  { "level": "N5", "main": "りっぱ", "kana": "りっぱ", "meaning": "宏伟 / 出色 / 优秀", "example": "立派な家ですね。(真是气派的房子啊。)" },
  { "level": "N5", "main": "留学生", "kana": "りゅうがくせい", "meaning": "留学生", "example": "私は日本の留学生です。(我是日本的留学生。)" },
  { "level": "N5", "main": "両親", "kana": "りょうしん", "meaning": "双亲 / 父母", "example": "田舎に両親がいます。(父母在乡下。)" },
  { "level": "N5", "main": "料理", "kana": "りょうり", "meaning": "料理 / 菜肴 / 做饭", "example": "母の料理はおいしいです。(妈妈做的菜很好吃。)" },
  { "level": "N5", "main": "旅行", "kana": "りょこう", "meaning": "旅行", "example": "夏休みに旅行をします。(暑假去旅行。)" },
  { "level": "N5", "main": "零", "kana": "れい", "meaning": "零", "example": "答えは零です。(答案是零。)" },
  { "level": "N5", "main": "冷蔵庫", "kana": "れいぞうこ", "meaning": "冰箱", "example": "冷蔵庫にジュースがあります。(冰箱里有果汁。)" },
  { "level": "N5", "main": "レコード", "kana": "レコード", "meaning": "唱片 / 记录", "example": "古いレコードを聞きます。(听老唱片。)" },
  { "level": "N5", "main": "レストラン", "kana": "レストラン", "meaning": "西餐厅 / 餐厅", "example": "レストランで食事をします。(在餐厅吃饭。)" },
  { "level": "N5", "main": "廊下", "kana": "ろうか", "meaning": "走廊", "example": "廊下を走らないでください。(请不要在走廊上跑。)" },
  { "level": "N5", "main": "ワイシャツ", "kana": "ワイシャツ", "meaning": "衬衫 (男式)", "example": "白いワイシャツを着ます。(穿白衬衫。)" },
  { "level": "N5", "main": "若い", "kana": "わかい", "meaning": "年轻", "example": "彼はまだ若いです。(他还很年轻。)" },
  { "level": "N5", "main": "分かる", "kana": "わかる", "meaning": "明白 / 懂", "example": "日本語が分かりますか。(你懂日语吗？)" },
  { "level": "N5", "main": "忘れる", "kana": "わすれる", "meaning": "忘记", "example": "宿題を忘れました。(忘记做作业了。)" },
  { "level": "N5", "main": "渡す", "kana": "わたす", "meaning": "交给 / 递给", "example": "先生に手紙を渡します。(把信交给老师。)" },
  { "level": "N5", "main": "渡る", "kana": "わたる", "meaning": "过 / 渡过", "example": "橋を渡ります。(过桥。)" },
  { "level": "N5", "main": "ほう", "kana": "ほう", "meaning": "方面 / 方", "example": "こちらのほうが大きいです。(这边的比较大。)" }
];